---
- name: Get current timestamp from the ansible host
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Query time & date from system
    shell: "date +%d-%m-%Y%Hh-%Mm-%Ss"
    register: tstamp

  - name: Set variables
    set_fact:
      cur_date: "{{ tstamp.stdout[0:10]}}"
      cur_time: "{{ tstamp.stdout[10:]}}"

- name: Backup configuration of Dell OS10 devices
  hosts: fabric
  vars:
    cur_date: "{{ hostvars['localhost']['cur_date'] }}"
    cur_time: "{{ hostvars['localhost']['cur_time'] }}"
    filesuffix: "_config-{{ cur_date }}-{{ cur_time }}.txt"
    backupdir: ./configs

  tasks:
  - name: Collecting configs from devices
    dellos10_command:
      commands:
        - show running-configuration
    
    register: config

  - name: Storing configs
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "{{ backupdir }}/{{ inventory_hostname }}{{ filesuffix }}"
...
